services:
  api:
    image: akash131/ams-server:${IMAGE_TAG:-latest}
    ports:
      - "3004:3004"
    env_file:
      - .env
    environment:
      IMAGE_TAG: ${IMAGE_TAG:-latest}
    restart: unless-stopped